ARG ARG_WWW_DIRPATH=/www
ARG ARG_SERVER_DIRPATH=/server
ARG ARG_SERVER_JAR=multi-threaded-java-web-server-0.1.jar

FROM maven:3.8.4-openjdk-17-slim
ENV DEBIAN_FRONTEND=noninteractive

ARG ARG_SERVER_DIRPATH
ENV SERVER_DIRPATH ${ARG_SERVER_DIRPATH}

ARG ARG_WWW_DIRPATH
ENV WWW_DIRPATH ${ARG_WWW_DIRPATH}

RUN mkdir ${WWW_DIRPATH}
RUN mkdir -p ${SERVER_DIRPATH}/src

COPY www/ ${WWW_DIRPATH}/
COPY src/ ${SERVER_DIRPATH}/src/
COPY pom.xml ${SERVER_DIRPATH}/

# specify correct www folder for the unit tests
RUN sed -i "s|<TestWebServerRoot>www</TestWebServerRoot>|<TestWebServerRoot>${WWW_DIRPATH}</TestWebServerRoot>}|g" ${SERVER_DIRPATH}/pom.xml

RUN mvn install -f ${SERVER_DIRPATH}/pom.xml

FROM maven:3.8.4-openjdk-17-slim

ARG ARG_SERVER_DIRPATH
ENV SERVER_DIRPATH ${ARG_SERVER_DIRPATH}

ARG ARG_SERVER_JAR
ENV SERVER_JAR ${ARG_SERVER_JAR}

ARG ARG_WWW_DIRPATH
ENV WWW_DIRPATH ${ARG_WWW_DIRPATH}

RUN mkdir ${WWW_DIRPATH}
RUN mkdir ${SERVER_DIRPATH}

COPY www/ ${WWW_DIRPATH}/
COPY config.json ${SERVER_DIRPATH}/

# import the compiled .jar into the new docker image
COPY --from=0 ${SERVER_DIRPATH}/target/ ${SERVER_DIRPATH}/

# specify correct www folder for deployment
RUN sed -i "s|www|${WWW_DIRPATH}|g" ${SERVER_DIRPATH}/config.json

EXPOSE 3000

CMD java -jar ${SERVER_DIRPATH}/${SERVER_JAR} -f ${SERVER_DIRPATH}/config.json