name: debug

on:
  push:
    branches:
      - 'main'
  
jobs:
  
  deploy:

    runs-on: ubuntu-latest
    
    steps:
      -
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install openssh-client -y
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SERVER_DEPLOY }}"
          sudo mkdir -p ~/.ssh
          sudo chmod 600 ~/.ssh
          sudo echo "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts
          sudo chmod 600 ~/.ssh/known_hosts
          if [ $(sudo ssh root@${{ secrets.SERVER_IP }} "docker ps -q -f name=website") ]; then
                sudo ssh root@${{ secrets.SERVER_IP }} "docker kill website"
                sudo ssh root@${{ secrets.SERVER_IP }} "docker rm website"
          fi
          sudo ssh root@${{ secrets.SERVER_IP }} "docker container prune --force"
          sudo ssh root@${{ secrets.SERVER_IP }} "docker image prune --force --all"
          sudo ssh root@${{ secrets.SERVER_IP }} "docker pull pragmaticfox/multi-threaded-java-web-server:latest
          sudo ssh root@${{ secrets.SERVER_IP }} "docker run -d -p 80:3000 --name website pragmaticfox/multi-threaded-java-web-server
