name: debug

on:
  push:
    branches:
      - 'main'
  
jobs:
  
  deploy:

    runs-on: ubuntu-latest
    steps:
      -
        shell: bash
        run: |
          sudo sshpass -p ${{ secrets.SERVER_TOKEN }} ssh root@${{ secrets.SERVER_IP }} "docker pull pragmaticfox/multi-threaded-java-web-server:latest"
          sudo sshpass -p ${{ secrets.SERVER_TOKEN }} ssh root@${{ secrets.SERVER_IP }} "docker run -d -p 80:3000 --name website pragmaticfox/multi-threaded-java-web-server"
