name: debug

on:
  push:
    branches:
      - 'main'
  
jobs:
  
  deploy:

    runs-on: ubuntu-latest
    steps:
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SERVER_DEPLOY }}
          ssh-host: ${{ secrets.SERVER_IP }}
      -
        shell: bash
        run: |
          if [ $(sudo ssh root@${{ secrets.SERVER_IP }} "docker ps -q -f name=website") ]; then
                sudo ssh root@${{ secrets.SERVER_IP }} "docker kill website"
                sudo ssh root@${{ secrets.SERVER_IP }} "docker rm website"
          fi
          sudo ssh root@${{ secrets.SERVER_IP }} "docker container prune --force"
          sudo ssh root@${{ secrets.SERVER_IP }} "docker image prune --force --all"
          sudo ssh root@${{ secrets.SERVER_IP }} "docker pull pragmaticfox/multi-threaded-java-web-server:latest"
          sudo ssh root@${{ secrets.SERVER_IP }} "docker run -d -p 80:3000 --name website pragmaticfox/multi-threaded-java-web-server"
