name: debug

on:
  push:
    branches:
      - 'main'
  
jobs:
  
  deploy:

    runs-on: ubuntu-latest
    steps:
      -
        shell: bash
        run: |
          echo "lol1"
          sshpass -p ${{ secrets.SERVER_TOKEN }} ssh root@${{ secrets.SERVER_IP }}
          echo "lol2"
          docker pull pragmaticfox/multi-threaded-java-web-server:latest
          echo "lol3"
          docker run -d -p 80:3000 --name website pragmaticfox/multi-threaded-java-web-server
          echo "lol4"
          exit
          echo "lol5"
